Add java installation to setup script
Running npm test without Java causes the following error message:

```
A service failed in the 'onPrepare' hook
Error: Selenium server did not start.
Another Selenium process may already be running or your java version may
be out of date.
Be sure to check the official Selenium release notes for minimum
required java version:
https://raw.githubusercontent.com/SeleniumHQ/selenium/master/java/CHANGELOG

    at ChildProcess.errorIfNeverStarted
      (/Users/nicholasduckwiler/Repos/why-test-web-app/node_modules/selenium-standalone/lib/start.js:158:10)
      at emitTwo (events.js:125:13)
      at ChildProcess.emit (events.js:213:7)
      at Process.ChildProcess._handle.onexit
      (internal/child_process.js:200:12)

Continue...
ERROR: connect ECONNREFUSED 127.0.0.1:4444
chrome
Error
```